/* All in One Place — shared site chrome, ads and local tools.
   No external fonts/CDNs are required. Put affiliate/ad URLs here. */
window.AI_AFFILIATE_LINKS = {
  chatgpt: "", claude: "", grammarly: "", copilot: "", canva: "", firefly: "",
  capcut: "", descript: "", perplexity: "", notebooklm: "", notion: "", otter: ""
};
window.AD_URLS = { top: "PASTE_TOP_AD_URL_HERE", middle: "PASTE_MIDDLE_AD_URL_HERE", bottom: "PASTE_BOTTOM_AD_URL_HERE" };
// Paste your YouTube channel URL here. Individual video URLs can be pasted on videos.html.
window.YOUTUBE_CHANNEL_URL = "https://www.youtube.com/@NoorHadithUrdu";

const AI_AFFILIATE_LINKS = window.AI_AFFILIATE_LINKS;
const AD_URLS = window.AD_URLS;
const NAV = [
  {label:'Home', href:'index.html'},
  {label:'Calculators', href:'calculator.html', menu:[['Scientific Calculator','calculator.html'],['Percentage Calculator','percentage-calculator.html'],['Age Calculator','age-calculator.html'],['BMI Calculator','bmi-calculator.html'],['EMI Calculator','emi-calculator.html'],['Tip Calculator','tip-calculator.html']]},
  {label:'Business', href:'business-calculators.html', menu:[['Business Calculators','business-calculators.html'],['GST Calculator','gst-calculator.html'],['Profit Margin','profit-margin-calculator.html'],['Markup','markup-calculator.html'],['Break-even','break-even-calculator.html'],['Invoice Calculator','invoice-calculator.html']]},
  {label:'AI Tools', href:'ai-tools-advice.html'},
  {label:'Website Tools', href:'website-tools.html'},
  {label:'Developer', href:'api-tools.html', menu:[['API Tools','api-tools.html'],['File Converter','file-converter.html']]},
  {label:'Testing', href:'testing-tools.html'},
  {label:'Career', href:'career-tools.html', menu:[['Career Tools','career-tools.html'],['Resume Builder','resume-builder.html']]},
  {label:'Credit Cards', href:'credit-cards.html'},
  {label:'Islamic', href:'islamic-tools.html'},
  {label:'Videos', href:'videos.html'}
];
function escapeHTML(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function currentFile(){return location.pathname.split('/').pop() || 'index.html';}
function renderHeader(){
  const old=document.querySelector('.site-header'); if(!old) return;
  const file=currentFile();
  const links=NAV.map((n,i)=>{
    const active=file===n.href || (n.menu&&n.menu.some(x=>x[1]===file));
    if(!n.menu) return `<a href="${n.href}" class="${active?'current':''}" ${active?'aria-current="page"':''}>${n.label}</a>`;
    return `<div class="nav-drop"><button type="button" class="nav-drop-btn ${active?'current':''}" aria-expanded="false">${n.label}<span aria-hidden="true">⌄</span></button><div class="nav-menu">${n.menu.map(x=>`<a href="${x[1]}" ${file===x[1]?'aria-current="page"':''}>${x[0]}</a>`).join('')}</div></div>`;
  }).join('');
  old.outerHTML=`<header class="site-header"><div class="site-header-inner"><a class="brand" href="index.html" aria-label="All in One Place home"><img class="brand-logo" src="assets/logo-all-in-one-place.svg" alt="All in One Place" width="248" height="48"></a><button class="mobile-menu-btn" type="button" aria-expanded="false" aria-label="Menu">☰ <span>Menu</span></button><nav class="site-nav" aria-label="Primary navigation">${links}</nav></div></header>`;
  document.querySelectorAll('.nav-drop-btn').forEach(btn=>btn.addEventListener('click',e=>{e.stopPropagation(); const open=btn.getAttribute('aria-expanded')==='true'; document.querySelectorAll('.nav-drop-btn').forEach(b=>b.setAttribute('aria-expanded','false')); btn.setAttribute('aria-expanded',String(!open));}));
  document.addEventListener('click',()=>document.querySelectorAll('.nav-drop-btn').forEach(b=>b.setAttribute('aria-expanded','false')));
  const mb=document.querySelector('.mobile-menu-btn'), nav=document.querySelector('.site-nav');
  mb?.addEventListener('click',()=>{const open=mb.getAttribute('aria-expanded')==='true';mb.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});
}
function isHttpUrl(url){return /^https?:\/\//i.test(String(url||''));}
function getYouTubeVideoId(value){
  const s=String(value||'').trim();
  if(!s || /^REPLACE_/i.test(s)) return '';
  if(/^[A-Za-z0-9_-]{11}$/.test(s)) return s;
  try{
    const u=new URL(s);
    const host=u.hostname.replace(/^www\./,'').toLowerCase();
    if(host==='youtu.be') return (u.pathname.split('/').filter(Boolean)[0]||'').slice(0,11);
    if(host==='youtube.com' || host==='m.youtube.com' || host==='music.youtube.com'){
      if(u.pathname==='/watch') return u.searchParams.get('v')||'';
      const parts=u.pathname.split('/').filter(Boolean);
      if(parts[0]==='shorts' || parts[0]==='embed' || parts[0]==='live') return (parts[1]||'').slice(0,11);
    }
  }catch{}
  return '';
}
function isDirectImageUrl(url){
  try{
    const u=new URL(url);
    return /\.(?:avif|gif|jpe?g|png|webp|svg)(?:$|\?)/i.test(u.pathname);
  }catch{return false;}
}
function adPreviewUrl(url){
  const yt=getYouTubeVideoId(url);
  if(yt) return `https://i.ytimg.com/vi/${encodeURIComponent(yt)}/hqdefault.jpg`;
  if(isDirectImageUrl(url)) return url;
  // Public, no-key screenshot fallback for ordinary web-page ad links.
  // Thum.io currently provides the first 1,000 screenshot hits/month free.
  return `https://image.thum.io/get/width/1200/crop/675/noanimate/?url=${encodeURIComponent(url)}`;
}
function renderAdContent(slot,key,url){
  slot.innerHTML='';
  const card=document.createElement('div'); card.className='ad-preview-card';
  const link=document.createElement('a'); link.className='ad-preview-link'; link.href=url; link.target='_blank'; link.rel='noopener sponsored';
  link.setAttribute('aria-label','Open advertisement');
  const img=document.createElement('img'); img.className='ad-preview-image'; img.loading='lazy'; img.alt='Advertisement preview'; img.src=adPreviewUrl(url);
  const label=document.createElement('span'); label.className='ad-preview-label'; label.textContent='Advertisement';
  link.appendChild(img); link.appendChild(label); card.appendChild(link);
  const open=document.createElement('a'); open.className='ad-open'; open.href=url; open.target='_blank'; open.rel='noopener sponsored'; open.textContent='Open ad'; card.appendChild(open);
  img.addEventListener('error',()=>{
    if(!isDirectImageUrl(url) && !getYouTubeVideoId(url)){
      const frame=document.createElement('iframe'); frame.className='ad-frame'; frame.src=url; frame.title='Advertisement'; frame.loading='lazy'; frame.setAttribute('sandbox','allow-scripts allow-forms allow-popups allow-popups-to-escape-sandbox');
      link.replaceChildren(frame);
    }else{
      img.remove(); label.textContent='Open advertisement';
    }
  },{once:true});
  slot.appendChild(card);
}
function renderAdSlots(){
  document.querySelectorAll('.ad-slot[data-ad]').forEach(slot=>{
    const key=slot.dataset.ad||'top',url=String(AD_URLS[key]||'').trim();
    if(!url || url.startsWith('PASTE_')){
      slot.innerHTML=`<div class="ad-placeholder"><strong>Advertisement</strong><span>Paste your ad link in <code>site.js</code> → AD_URLS.${key}</span></div>`;
      return;
    }
    if(!isHttpUrl(url)){
      slot.innerHTML=`<div class="ad-placeholder"><strong>Advertisement</strong><span>Use a valid http(s) ad URL in <code>site.js</code>.</span></div>`;
      return;
    }
    renderAdContent(slot,key,url);
  });
  const footer=document.querySelector('.site-footer');
  if(footer&&!document.querySelector('.ad-slot[data-ad="bottom"]')){
    const d=document.createElement('div'); d.className='wrap'; d.innerHTML='<div class="ad-slot" data-ad="bottom"></div>';
    footer.parentNode.insertBefore(d,footer);
    const s=d.querySelector('.ad-slot'),url=String(AD_URLS.bottom||'').trim();
    if(!url || url.startsWith('PASTE_')) s.innerHTML=`<div class="ad-placeholder"><strong>Advertisement</strong><span>Paste your ad link in <code>site.js</code> → AD_URLS.bottom</span></div>`;
    else if(isHttpUrl(url)) renderAdContent(s,'bottom',url);
  }
}
function downloadText(name,text,mime='text/plain'){const blob=new Blob([text],{type:mime});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
function showTool(title,body,init){
  let modal=document.getElementById('tool-modal'); if(!modal){modal=document.createElement('div');modal.id='tool-modal';modal.className='tool-modal';modal.innerHTML='<div class="tool-modal-backdrop" data-close></div><section class="tool-modal-card" role="dialog" aria-modal="true" aria-labelledby="tool-modal-title"><button class="tool-modal-close" data-close aria-label="Close">×</button><div id="tool-modal-title"></div><div id="tool-modal-body"></div></section>';document.body.appendChild(modal);modal.addEventListener('click',e=>{if(e.target.hasAttribute('data-close')) modal.classList.remove('open')});}
  modal.querySelector('#tool-modal-title').innerHTML=`<h2>${escapeHTML(title)}</h2>`;modal.querySelector('#tool-modal-body').innerHTML=body;modal.classList.add('open');init?.(modal.querySelector('#tool-modal-body'));modal.querySelector('.tool-modal-close').focus();
}
function buttonToolHandlers(){document.querySelectorAll('.tool-open[data-tool]').forEach(btn=>btn.addEventListener('click',()=>openTool(btn.dataset.tool)));document.querySelectorAll('.generic-tool[data-name]').forEach(btn=>btn.addEventListener('click',()=>openTool(btn.dataset.name)));}
function field(label,id,type='text',value='',extra=''){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${escapeHTML(value)}" ${extra}></div>`}
function openTool(key){
  const k=String(key).toLowerCase().replace(/[^a-z0-9]+/g,'-');
  const defs={
    'tasbeeh':()=>showTool('Tasbeeh Counter','<div class="tasbeeh-count" id="count">0</div><div class="action-row" style="justify-content:center"><button class="primary-btn" id="plus">+1</button><button class="secondary-btn" id="minus">−1</button><button class="secondary-btn" id="reset">Reset</button></div><div class="field"><label for="target">Target</label><input id="target" type="number" min="1" value="33"></div><div class="output-box" id="out">0 / 33</div>',b=>{let c=0;const out=()=>{const t=Math.max(1,+b.querySelector('#target').value||33);b.querySelector('#count').textContent=c;b.querySelector('#out').textContent=`${c} / ${t}${c>=t?' • Target reached':''}`};b.querySelector('#plus').onclick=()=>{c++;out()};b.querySelector('#minus').onclick=()=>{c=Math.max(0,c-1);out()};b.querySelector('#reset').onclick=()=>{c=0;out()};b.querySelector('#target').oninput=out;out()}),
    'zakat':()=>showTool('Zakat Calculator','<div class="tool-grid-compact">'+field('Cash & bank balances (₹)','cash','number','0','min="0" step="0.01"')+field('Gold/silver & eligible assets (₹)','assets','number','0','min="0" step="0.01"')+field('Business/investment assets (₹)','business','number','0','min="0" step="0.01"')+field('Eligible short-term debts (₹)','debts','number','0','min="0" step="0.01"')+'</div><button class="primary-btn" id="go">Calculate estimated zakat</button><div class="output-box" id="out"></div><p class="small-note">This is a simple 2.5% estimate. Nisab, asset eligibility and debt treatment can vary; consult a qualified scholar for your circumstances.</p>',b=>b.querySelector('#go').onclick=()=>{const n=Math.max(0,...['cash','assets','business'].map(id=>+b.querySelector('#'+id).value||0).reduce((a,v)=>a+v,0)- (+b.querySelector('#debts').value||0));b.querySelector('#out').textContent=`Zakatable amount: ₹${n.toFixed(2)}\nEstimated zakat (2.5%): ₹${(n*.025).toFixed(2)}`}),
    'hijri':()=>showTool('Hijri / Gregorian Helper','<div class="field"><label for="date">Gregorian date</label><input id="date" type="date"></div><button class="primary-btn" id="go">Convert</button><div class="output-box" id="out"></div><p class="small-note">Browser calendar support varies. Religious dates can differ by moon sighting and local authority.</p>',b=>{b.querySelector('#date').value=new Date().toISOString().slice(0,10);b.querySelector('#go').onclick=()=>{const d=b.querySelector('#date').valueAsDate;if(!d){b.querySelector('#out').textContent='Select a date.';return}b.querySelector('#out').textContent=d.toLocaleDateString(undefined,{dateStyle:'full'})}}),
    'prayer':()=>showTool('Prayer Times Helper','<div class="field"><label for="city">City</label><input id="city" value="Mumbai"></div><div class="field"><label for="zone">Time zone</label><input id="zone" value="Asia/Kolkata"></div><div class="output-box" id="out">Enter your city and use your trusted local prayer-time source. This page intentionally avoids a network API so the website preview does not request external access.</div><button class="secondary-btn" id="open">Open search</button>',b=>b.querySelector('#open').onclick=()=>{const c=encodeURIComponent(b.querySelector('#city').value.trim()||'your city');window.open('https://www.google.com/search?q='+c+'+prayer+times','_blank','noopener')}),
    'qibla':()=>showTool('Qibla Helper','<div class="qibla-compass"><div class="qibla-arrow">↗</div><strong>Kaaba bearing</strong><span>From India, Qibla is generally toward the west / north-west depending on location.</span></div><div class="field"><label for="city">City</label><input id="city" value="Mumbai"></div><button class="secondary-btn" id="open">Search precise Qibla direction</button><p class="small-note">For precise direction, use a trusted Qibla app with device sensors and location.</p>',b=>b.querySelector('#open').onclick=()=>window.open('https://www.google.com/search?q='+encodeURIComponent((b.querySelector('#city').value||'your city')+' Qibla direction'),'_blank','noopener')),
    'ramadan':()=>showTool('Ramadan Countdown','<div class="field"><label for="date">Target Ramadan start date</label><input id="date" type="date"></div><div class="countdown-box" id="out">Select the expected date.</div><button class="primary-btn" id="go">Calculate countdown</button><p class="small-note">Ramadan dates are based on lunar observation and may vary by location.</p>',b=>{const now=new Date();const guess=new Date(now.getFullYear()+ (now.getMonth()>3?1:0),1,18);b.querySelector('#date').value=guess.toISOString().slice(0,10);b.querySelector('#go').onclick=()=>{const d=b.querySelector('#date').valueAsDate;if(!d){return}const diff=Math.ceil((d-new Date())/86400000);b.querySelector('#out').textContent=diff>=0?`${diff} day(s) until the selected date.`:'That date has passed — choose the next expected Ramadan date.'}}),
    'quiz':()=>showTool('Islamic Quiz','<div id="qbox" class="output-box"></div><div class="action-row" id="opts"></div><div class="output-box" id="score">Score: 0</div>',b=>{const qs=[['How many obligatory prayers are there each day?',['3','5','7','2'],1],['Which month is Ramadan?',['9th Hijri month','1st Hijri month','12th Hijri month','6th Hijri month'],0],['How many surahs are in the Quran?',['110','114','120','99'],1]];let i=0,score=0;const render=()=>{const q=qs[i];b.querySelector('#qbox').textContent=`${i+1}. ${q[0]}`;b.querySelector('#opts').innerHTML=q[1].map((x,n)=>`<button class="secondary-btn" data-n="${n}">${x}</button>`).join('');b.querySelectorAll('[data-n]').forEach(x=>x.onclick=()=>{if(+x.dataset.n===q[2])score++;i++;if(i<qs.length)render();else{b.querySelector('#qbox').textContent='Quiz complete';b.querySelector('#opts').innerHTML='';b.querySelector('#score').textContent=`Score: ${score} / ${qs.length}`}});b.querySelector('#score').textContent=`Score: ${score}`};render()}),
    'quran':()=>showTool('Quran Resource','<p>Use your preferred verified Quran source or your own recitation library.</p><div class="action-row"><button class="primary-btn" id="open">Open Quran.com</button></div>',b=>b.querySelector('#open').onclick=()=>window.open('https://quran.com/','_blank','noopener')),
    'hadith':()=>showTool('Hadith Resource','<p>Use a trusted Hadith library and verify references before publishing religious claims.</p><button class="primary-btn" id="open">Open Sunnah.com</button>',b=>b.querySelector('#open').onclick=()=>window.open('https://sunnah.com/','_blank','noopener')),
    'dua':()=>showTool('Daily Dua','<div class="output-box"><strong>Start your own verified Dua library here.</strong><br><br>Keep Arabic, transliteration, meaning and reference together. You can later replace this panel with your own Daily Duas content.</div>'),
    'islamic-videos':()=>window.location.href='videos.html',
    'password':()=>showTool('Password Generator',field('Length','len','number','18','min="8" max="128"')+'<div class="action-row"><button class="primary-btn" id="gen">Generate password</button><button class="secondary-btn" id="copy">Copy</button></div><div class="output-box mono" id="out">Click Generate.</div>',b=>{b.querySelector('#gen').onclick=()=>{const n=Math.min(128,Math.max(8,+b.querySelector('#len').value||18));const chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%^&*_-+=';let r='';const a=new Uint32Array(n);crypto.getRandomValues(a);for(let i=0;i<n;i++)r+=chars[a[i]%chars.length];b.querySelector('#out').textContent=r};b.querySelector('#copy').onclick=()=>navigator.clipboard?.writeText(b.querySelector('#out').textContent)}),
    'uuid':()=>showTool('UUID Generator','<div class="action-row"><button class="primary-btn" id="gen">Generate UUID</button><button class="secondary-btn" id="copy">Copy</button></div><div class="output-box mono" id="out">Click Generate.</div>',b=>{const gen=()=>b.querySelector('#out').textContent=crypto.randomUUID?crypto.randomUUID():([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g,c=>(c^(crypto.getRandomValues(new Uint8Array(1))[0]&15)>>c/4).toString(16));b.querySelector('#gen').onclick=gen;b.querySelector('#copy').onclick=()=>navigator.clipboard?.writeText(b.querySelector('#out').textContent);gen()}),
    'jsonfmt':()=>showTool('JSON Formatter','<div class="field"><label for="input">JSON</label><textarea id="input">{"name":"All in One Place","tools":[]}</textarea></div><div class="action-row"><button class="primary-btn" id="go">Format</button><button class="secondary-btn" id="min">Minify</button></div><div class="output-box mono" id="out"></div>',b=>{const run=min=>{try{const v=JSON.parse(b.querySelector('#input').value);b.querySelector('#out').textContent=min?JSON.stringify(v):JSON.stringify(v,null,2)}catch(e){b.querySelector('#out').textContent='Invalid JSON: '+e.message}};b.querySelector('#go').onclick=()=>run(false);b.querySelector('#min').onclick=()=>run(true)}),
    'jsonvalid':()=>showTool('JSON Validator','<div class="field"><label for="input">JSON</label><textarea id="input"></textarea></div><button class="primary-btn" id="go">Validate</button><div class="output-box" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{try{JSON.parse(b.querySelector('#input').value);b.querySelector('#out').textContent='✓ Valid JSON'}catch(e){b.querySelector('#out').textContent='✗ Invalid JSON: '+e.message}}),
    'base64':()=>showTool('Base64 Encoder / Decoder','<div class="field"><label for="input">Text</label><textarea id="input"></textarea></div><div class="action-row"><button class="primary-btn" id="enc">Encode</button><button class="secondary-btn" id="dec">Decode</button></div><div class="output-box mono" id="out"></div>',b=>{b.querySelector('#enc').onclick=()=>{try{b.querySelector('#out').textContent=btoa(unescape(encodeURIComponent(b.querySelector('#input').value)))}catch{b.querySelector('#out').textContent='Could not encode.'}};b.querySelector('#dec').onclick=()=>{try{b.querySelector('#out').textContent=decodeURIComponent(escape(atob(b.querySelector('#input').value.trim())))}catch{b.querySelector('#out').textContent='Invalid Base64.'}}}),
    'timestamp':()=>showTool('Timestamp Converter',field('Unix timestamp (seconds)','ts','number',Math.floor(Date.now()/1000))+'<div class="action-row"><button class="primary-btn" id="toDate">Timestamp → Date</button><button class="secondary-btn" id="toTs">Now → Timestamp</button></div><div class="output-box" id="out"></div>',b=>{b.querySelector('#toDate').onclick=()=>{const n=Number(b.querySelector('#ts').value);b.querySelector('#out').textContent=Number.isFinite(n)?new Date(n*1000).toString():'Invalid timestamp'};b.querySelector('#toTs').onclick=()=>{const n=Math.floor(Date.now()/1000);b.querySelector('#ts').value=n;b.querySelector('#out').textContent=String(n)}}),
    'color':()=>showTool('Color Converter',field('HEX color','hex','text','#1769aa','pattern="^#?[0-9a-fA-F]{6}$"')+'<button class="primary-btn" id="go">Convert</button><div class="output-box" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{let h=b.querySelector('#hex').value.replace('#','');if(!/^[0-9a-fA-F]{6}$/.test(h)){b.querySelector('#out').textContent='Enter a 6-digit HEX value.';return}const r=parseInt(h.slice(0,2),16),g=parseInt(h.slice(2,4),16),bl=parseInt(h.slice(4),16);b.querySelector('#out').textContent=`RGB(${r}, ${g}, ${bl}) • HSL ${rgbToHsl(r,g,bl)}`}),
    'htmlfmt':()=>showTool('HTML Formatter','<div class="field"><label for="input">HTML</label><textarea id="input">&lt;div&gt;&lt;h1&gt;Hello&lt;/h1&gt;&lt;p&gt;Text&lt;/p&gt;&lt;/div&gt;</textarea></div><button class="primary-btn" id="go">Format HTML</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{let s=b.querySelector('#input').value.replace(/>\s*</g,'><').trim(),depth=0,out='';s.split(/(?=<)|(?<=>)/).filter(Boolean).forEach(x=>{if(x.match(/^<\//))depth=Math.max(0,depth-1);out+='  '.repeat(depth)+x.trim()+'\n';if(x.match(/^<[^!?/][^>]*>$/)&&!x.match(/<[^>]+\/>$/)&&!x.match(/^<(input|img|br|hr|meta|link)\b/i))depth++});b.querySelector('#out').textContent=out}),
    'meta':()=>showTool('Meta Tag Generator',field('Page title','title','text','All in One Place')+field('Description','desc','text','Useful calculators and tools')+field('Canonical URL','url','url','https://example.com/')+'<button class="primary-btn" id="go">Generate tags</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const e=id=>escapeHTML(b.querySelector('#'+id).value.trim());b.querySelector('#out').textContent=`<title>${e('title')}</title>\n<meta name="description" content="${e('desc')}">\n<link rel="canonical" href="${e('url')}">`}),
    'robots':()=>showTool('Robots.txt Generator',field('User-agent','ua','text','*')+field('Disallow path','dis','text','/admin/')+field('Sitemap URL','sm','url','https://example.com/sitemap.xml')+'<button class="primary-btn" id="go">Generate robots.txt</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const o=`User-agent: ${b.querySelector('#ua').value||'*'}\nDisallow: ${b.querySelector('#dis').value||'/'}\n\nSitemap: ${b.querySelector('#sm').value}`;b.querySelector('#out').textContent=o;downloadText('robots.txt',o)}),
    'sitemap':()=>showTool('Sitemap Generator','<div class="field"><label for="urls">One URL per line</label><textarea id="urls">https://example.com/\nhttps://example.com/about</textarea></div><button class="primary-btn" id="go">Generate sitemap.xml</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const urls=b.querySelector('#urls').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);const xml='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(u=>`  <url><loc>${escapeHTML(u)}</loc></url>`).join('\n')+'\n</urlset>';b.querySelector('#out').textContent=xml;downloadText('sitemap.xml',xml,'application/xml')}),
    'favicon':()=>showTool('Favicon Generator',field('Initials','txt','text','AIO')+'<button class="primary-btn" id="go">Create favicon</button><div class="output-box" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const t=(b.querySelector('#txt').value||'A').slice(0,3).toUpperCase();const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="256" height="256"><rect width="256" height="256" rx="48" fill="#1769aa"/><text x="128" y="150" text-anchor="middle" font-family="Arial" font-size="82" font-weight="700" fill="white">${escapeHTML(t)}</text></svg>`;const url='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);b.querySelector('#out').innerHTML=`<img class="favicon-preview" src="${url}" alt="Favicon preview"><br><a class="primary-btn inline-btn" download="favicon.svg" href="${url}">Download favicon.svg</a>`}),
    'business':()=>showTool('Business Name Generator',field('Industry','industry','text','Technology')+field('Keyword','word','text','Smart')+'<button class="primary-btn" id="go">Generate names</button><div class="output-box" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const a=['Nova','Vertex','Bright','Prime','Nexa','Pulse','Orbit','Core','Vista','Forge'];const w=b.querySelector('#word').value.trim()||'Smart',ind=b.querySelector('#industry').value.trim()||'Business';const arr=Array.from({length:10},(_,i)=>`${a[i]} ${w} ${ind}`).join('\n');b.querySelector('#out').textContent=arr}),
    'shortener':()=>showTool('URL Shortener',field('Long URL','url','url','https://example.com')+'<button class="primary-btn" id="go">Shorten URL</button><div class="output-box" id="out">This tool uses the is.gd public endpoint when available.</div>',b=>b.querySelector('#go').onclick=async()=>{const u=b.querySelector('#url').value.trim(),o=b.querySelector('#out');if(!/^https?:\/\//i.test(u)){o.textContent='Enter a valid http(s) URL.';return}o.textContent='Creating short URL…';try{const r=await fetch('https://is.gd/create.php?format=json&url='+encodeURIComponent(u));const j=await r.json();o.textContent=j.shorturl||j.errormessage||'Shortener service did not return a URL.'}catch{o.textContent='The browser could not reach the shortener. Try again or connect your own URL-shortening API.'}}),
    'qr':()=>showTool('QR Code Generator',field('Text or URL','txt','text','https://example.com')+'<button class="primary-btn" id="go">Generate QR</button><div class="output-box" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const v=b.querySelector('#txt').value.trim();if(!v){b.querySelector('#out').textContent='Enter text or a URL.';return}const src='https://api.qrserver.com/v1/create-qr-code/?size=320x320&data='+encodeURIComponent(v);b.querySelector('#out').innerHTML=`<img class="generated-image" src="${src}" alt="QR code"><br><a class="secondary-btn inline-btn" href="${src}" target="_blank" rel="noopener">Open QR image</a>`}),
    'barcode':()=>showTool('Barcode Generator',field('Code 128 value','txt','text','AIO-12345')+'<button class="primary-btn" id="go">Generate barcode</button><div class="output-box" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const v=b.querySelector('#txt').value.trim();if(!v){b.querySelector('#out').textContent='Enter a value.';return}const src='https://barcode.tec-it.com/barcode.ashx?data='+encodeURIComponent(v)+'&code=Code128&translate-esc=on';b.querySelector('#out').innerHTML=`<img class="generated-image barcode-image" src="${src}" alt="Barcode"><br><a class="secondary-btn inline-btn" href="${src}" target="_blank" rel="noopener">Open barcode</a>`}),
    'invoice':()=>showTool('Invoice Generator','<div class="tool-grid-compact">'+field('Business','biz','text','My Business')+field('Customer','cust','text','Customer')+field('Item','item','text','Service')+field('Quantity','qty','number','1','min="1"')+field('Unit price (₹)','price','number','1000','min="0" step="0.01"')+field('GST %','gst','number','18','min="0" step="0.01"')+'</div><div class="action-row"><button class="primary-btn" id="calc">Preview invoice</button></div><div id="invoicePreview" class="invoice-preview"></div>',b=>b.querySelector('#calc').onclick=()=>{const q=+b.querySelector('#qty').value||0,p=+b.querySelector('#price').value||0,g=+b.querySelector('#gst').value||0,sub=q*p,tax=sub*g/100,total=sub+tax; b.querySelector('#invoicePreview').innerHTML=`<h3>${escapeHTML(b.querySelector('#biz').value)}</h3><p>Bill to: ${escapeHTML(b.querySelector('#cust').value)}</p><table><tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr><tr><td>${escapeHTML(b.querySelector('#item').value)}</td><td>${q}</td><td>₹${p.toFixed(2)}</td><td>₹${sub.toFixed(2)}</td></tr></table><p>GST: ₹${tax.toFixed(2)}</p><h3>Total: ₹${total.toFixed(2)}</h3><button class="secondary-btn" onclick="window.print()">Print / Save PDF</button>`}),
    'api-response-formatter':()=>showTool('API Response Formatter','<div class="field"><label for="input">Paste JSON response</label><textarea id="input"></textarea></div><button class="primary-btn" id="go">Format response</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{try{b.querySelector('#out').textContent=JSON.stringify(JSON.parse(b.querySelector('#input').value),null,2)}catch{b.querySelector('#out').textContent='Not valid JSON. Raw response:\n\n'+b.querySelector('#input').value}}),
    'jwt-decoder':()=>showTool('JWT Decoder','<div class="field"><label for="input">JWT</label><textarea id="input" placeholder="eyJhbGciOi..."></textarea></div><button class="primary-btn" id="go">Decode</button><div class="output-box mono" id="out"></div><p class="small-note">Decoding is local. This does not verify the signature.</p>',b=>b.querySelector('#go').onclick=()=>{try{const [h,p]=b.querySelector('#input').value.trim().split('.');const dec=x=>JSON.stringify(JSON.parse(decodeURIComponent(escape(atob(x.replace(/-/g,'+').replace(/_/g,'/'))))),null,2);b.querySelector('#out').textContent='HEADER\n'+dec(h)+'\n\nPAYLOAD\n'+dec(p)}catch{b.querySelector('#out').textContent='Invalid JWT.'}}),
    'http-status-checker':()=>showTool('HTTP Status Checker',field('URL','url','url','https://example.com')+'<button class="primary-btn" id="go">Check</button><div class="output-box" id="out"></div>',b=>b.querySelector('#go').onclick=async()=>{const u=b.querySelector('#url').value.trim(),o=b.querySelector('#out');if(!/^https?:\/\//i.test(u)){o.textContent='Enter a valid URL.';return}o.textContent='Checking…';const t=Date.now();try{const r=await fetch(u,{method:'HEAD',mode:'cors'});o.textContent=`HTTP ${r.status} ${r.statusText||''}\nResponse time: ${Date.now()-t} ms`}catch{o.textContent='The browser could not read the HTTP status (often caused by CORS). The site may still be online. Connect a server-side checker for authoritative status codes.'}}),
    'regex-tester':()=>showTool('Regex Tester',field('Regular expression','re','text','^[A-Z][a-z]+$')+field('Flags','flags','text','')+'<div class="field"><label for="sample">Test text</label><textarea id="sample">John\nAlice\n123</textarea></div><button class="primary-btn" id="go">Test regex</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{try{const r=new RegExp(b.querySelector('#re').value,b.querySelector('#flags').value);const s=b.querySelector('#sample').value;const m=[...s.matchAll(new RegExp(r.source,r.flags.includes('g')?r.flags:r.flags+'g'))];b.querySelector('#out').textContent=(m.length?m.map(x=>x[0]).join('\n'):'No matches')}catch(e){b.querySelector('#out').textContent='Regex error: '+e.message}}),
    'test-case-generator':()=>showTool('Test-case Generator','<div class="field"><label for="req">Requirement</label><textarea id="req" placeholder="Example: User can reset password with a registered email."></textarea></div><button class="primary-btn" id="go">Generate test cases</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const r=b.querySelector('#req').value.trim();if(!r){b.querySelector('#out').textContent='Enter a requirement.';return}b.querySelector('#out').textContent=`TC-01 Positive: ${r}\nTC-02 Missing required input\nTC-03 Invalid input format\nTC-04 Boundary/minimum value\nTC-05 Boundary/maximum value\nTC-06 Unauthorized user\nTC-07 Network/server error\nTC-08 Refresh/retry behavior\nTC-09 Accessibility/keyboard behavior\nTC-10 Regression check for related flow`}),
    'bug-report-generator':()=>showTool('Bug Report Generator','<div class="tool-grid-compact">'+field('Title','title','text','')+field('Environment','env','text','Chrome / Windows')+'</div><div class="field"><label for="steps">Steps to reproduce</label><textarea id="steps"></textarea></div><div class="field"><label for="expected">Expected</label><textarea id="expected"></textarea></div><div class="field"><label for="actual">Actual</label><textarea id="actual"></textarea></div><button class="primary-btn" id="go">Generate report</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const g=id=>b.querySelector('#'+id).value.trim();b.querySelector('#out').textContent=`Title: ${g('title')}\nEnvironment: ${g('env')}\n\nSteps:\n${g('steps')}\n\nExpected:\n${g('expected')}\n\nActual:\n${g('actual')}\n\nSeverity: [set]\nPriority: [set]`}),
    'test-data-generator':()=>showTool('Test Data Generator','<div class="tool-grid-compact">'+field('Rows','rows','number','10','min="1" max="100"')+field('Prefix','prefix','text','user')+'</div><button class="primary-btn" id="go">Generate CSV</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const n=Math.min(100,Math.max(1,+b.querySelector('#rows').value||10)),p=b.querySelector('#prefix').value||'user';const lines=['id,name,email'];for(let i=1;i<=n;i++)lines.push(`${i},${p} ${i},${p}${i}@example.com`);const csv=lines.join('\n');b.querySelector('#out').textContent=csv;downloadText('test-data.csv',csv,'text/csv')}),
    'sql-query-generator':()=>showTool('SQL Query Generator','<div class="field"><label for="intent">Describe the query</label><textarea id="intent" placeholder="Find active users created in the last 30 days"></textarea></div><div class="field"><label for="table">Table</label><input id="table" value="users"></div><button class="primary-btn" id="go">Generate SQL</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const t=b.querySelector('#table').value.trim()||'table';const i=b.querySelector('#intent').value.toLowerCase();let q=`SELECT * FROM ${t};`;if(i.includes('active'))q=`SELECT * FROM ${t} WHERE active = TRUE;`;if(i.includes('last 30'))q=`SELECT * FROM ${t} WHERE created_at >= CURRENT_DATE - INTERVAL '30 days';`;b.querySelector('#out').textContent=q}),
    'random-test-data-generator':()=>showTool('Random Test Data',field('Rows','rows','number','20','min="1" max="200"')+'<button class="primary-btn" id="go">Generate</button><div class="output-box mono" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const n=Math.min(200,Math.max(1,+b.querySelector('#rows').value||20));const lines=['id,name,email,age'];for(let i=1;i<=n;i++){const name=['Aarav','Maya','Rohan','Sara','Kabir'][i%5];lines.push(`${i},${name} ${i},${name.toLowerCase()}${i}@example.com,${18+(i*7)%50}`)}const csv=lines.join('\n');b.querySelector('#out').textContent=csv;downloadText('random-test-data.csv',csv,'text/csv')}),
    'qa-interview-question-generator':()=>showTool('QA Interview Question Generator','<div class="field"><label for="topic">Topic</label><select id="topic"><option>Manual Testing</option><option>Python / pytest</option><option>Playwright</option><option>API Testing</option><option>SQL / Database</option><option>Automation Frameworks</option></select></div><button class="primary-btn" id="go">Generate questions</button><div class="output-box" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const q={"Manual Testing":['Explain severity vs priority.','Design test cases for a login form.','How do you test a payment failure?'],"Python / pytest":['Write a pytest fixture for a database connection.','How do you parameterize pytest tests?','How would you mock an API?'],"Playwright":['How do you wait for a dynamic element?','How do you design Page Objects?','How do you capture traces on failure?'],"API Testing":['How do you validate status, headers and schema?','How do you test auth and token expiry?','How do you design negative API tests?'],"SQL / Database":['Write a query to find duplicates.','How do you validate an API result against a database?','Explain joins and indexes.'],"Automation Frameworks":['How would you structure a maintainable framework?','How do you handle test data?','How do you parallelize safely?']}[b.querySelector('#topic').value];b.querySelector('#out').textContent=q.map((x,i)=>`${i+1}. ${x}`).join('\n')}),
    'mock-interview':()=>showTool('Mock Interview','<div class="field"><label for="role">Role</label><input id="role" value="QA Automation Engineer"></div><div class="output-box" id="question">Click Start to get question 1.</div><div class="action-row"><button class="primary-btn" id="start">Start / Next</button><button class="secondary-btn" id="reset">Reset</button></div><div class="field"><label for="answer">Your answer</label><textarea id="answer"></textarea></div><div class="output-box" id="score"></div>',b=>{let i=0;const qs=['Tell me about your automation framework.','Describe a difficult bug you diagnosed.','Write a SQL query to find duplicate records.','How would you test an API end to end?','How do you reduce flaky UI tests?'];b.querySelector('#start').onclick=()=>{b.querySelector('#question').textContent=`Question ${++i}: ${qs[(i-1)%qs.length]}`;b.querySelector('#score').textContent='Tip: answer with context, action, result and measurable impact.'};b.querySelector('#reset').onclick=()=>{i=0;b.querySelector('#question').textContent='Click Start to get question 1.';b.querySelector('#answer').value='';b.querySelector('#score').textContent=''}}),
    'resume-analyzer':()=>showTool('Resume Analyzer','<div class="field"><label for="resume">Resume text</label><textarea id="resume"></textarea></div><div class="field"><label for="jd">Job description (optional)</label><textarea id="jd"></textarea></div><button class="primary-btn" id="go">Analyze</button><div class="output-box" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const r=b.querySelector('#resume').value.trim(),j=b.querySelector('#jd').value.toLowerCase();if(!r){b.querySelector('#out').textContent='Paste your resume text first.';return}const words=r.split(/\s+/).length,skills=['python','pytest','playwright','api','sql','selenium','javascript','automation','testing'].filter(x=>r.toLowerCase().includes(x));const missing=j?[...new Set((j.match(/\b[a-z][a-z0-9+#.-]{2,}\b/gi)||[]).map(x=>x.toLowerCase()))].filter(x=>!r.toLowerCase().includes(x)).slice(0,12):[];b.querySelector('#out').textContent=`Approx. words: ${words}\nDetected skills: ${skills.join(', ')||'None'}\n\nPotential JD keywords not found: ${missing.join(', ')||'None detected'}\n\nImprove with measurable outcomes, relevant keywords and concise project bullets.`}),
    'job-description-analyzer':()=>showTool('Job Description Analyzer','<div class="field"><label for="jd">Job description</label><textarea id="jd"></textarea></div><button class="primary-btn" id="go">Analyze</button><div class="output-box" id="out"></div>',b=>b.querySelector('#go').onclick=()=>{const t=b.querySelector('#jd').value.toLowerCase();if(!t){b.querySelector('#out').textContent='Paste a job description first.';return}const words=t.split(/\s+/).filter(Boolean),skills=['python','pytest','playwright','selenium','api','sql','javascript','typescript','java','aws','azure','docker','git','jira','postman','rest','graphql','automation','testing'];const found=skills.filter(x=>t.includes(x));b.querySelector('#out').textContent=`Approx. words: ${words.length}\nDetected skills: ${found.join(', ')||'None'}\n\nAction verbs: ${['design','develop','test','automate','validate','debug','lead','build','analyze'].filter(x=>t.includes(x)).join(', ')||'None'}`}),
  };
  if(k==='tasbeeh') return defs.tasbeeh(); if(k==='zakat') return defs.zakat(); if(k==='hijri') return defs.hijri(); if(k==='prayer') return defs.prayer(); if(k==='qibla') return defs.qibla(); if(k==='ramadan') return defs.ramadan(); if(k==='quiz') return defs.quiz(); if(k==='quran') return defs.quran(); if(k==='hadith') return defs.hadith(); if(k==='dua') return defs.dua(); if(k==='islamic-videos') return defs['islamic-videos']();
  if(k==='json-formatter') return defs.jsonfmt(); if(k==='json-validator') return defs.jsonvalid(); if(k==='api-response-formatter') return defs['api-response-formatter'](); if(k==='jwt-decoder') return defs['jwt-decoder'](); if(k==='http-status-checker') return defs['http-status-checker'](); if(k==='regex-tester') return defs['regex-tester'](); if(k==='test-case-generator') return defs['test-case-generator'](); if(k==='bug-report-generator') return defs['bug-report-generator'](); if(k==='test-data-generator') return defs['test-data-generator'](); if(k==='sql-query-generator') return defs['sql-query-generator'](); if(k==='random-test-data-generator') return defs['random-test-data-generator'](); if(k==='qa-interview-question-generator') return defs['qa-interview-question-generator'](); if(k==='mock-interview') return defs['mock-interview'](); if(k==='resume-analyzer') return defs['resume-analyzer'](); if(k==='job-description-analyzer') return defs['job-description-analyzer'](); if(k==='jsonfmt') return defs.jsonfmt(); if(k==='jsonvalid') return defs.jsonvalid(); if(k==='base64') return defs.base64(); if(k==='timestamp') return defs.timestamp(); if(k==='color') return defs.color(); if(k==='htmlfmt') return defs.htmlfmt(); if(k==='meta') return defs.meta(); if(k==='robots') return defs.robots(); if(k==='sitemap') return defs.sitemap(); if(k==='favicon') return defs.favicon(); if(k==='business') return defs.business(); if(k==='shortener') return defs.shortener(); if(k==='qr') return defs.qr(); if(k==='barcode') return defs.barcode(); if(k==='invoice') return defs.invoice(); if(k==='password') return defs.password(); if(k==='uuid') return defs.uuid();
}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const max=Math.max(r,g,b),min=Math.min(r,g,b);let h,s,l=(max+min)/2;if(max===min)h=s=0;else{const d=max-min;s=l>.5?d/(2-max-min):d/(max+min);switch(max){case r:h=(g-b)/d+(g<b?6:0);break;case g:h=(b-r)/d+2;break;default:h=(r-g)/d+4}h/=6}return `${Math.round(h*360)}°, ${Math.round(s*100)}%, ${Math.round(l*100)}%`}
function ensureCollectionBindings(){buttonToolHandlers();}
function initSite(){renderHeader();renderAdSlots();ensureCollectionBindings();}
if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',initSite); else initSite();
